In [1]:
import pandas as pd

In [54]:
import os
print(os.getcwd())
os.chdir("project/backend")
print(os.getcwd())

c:\Users\Lenovo\Documents\02 Programming\CPF Government app
c:\Users\Lenovo\Documents\02 Programming\CPF Government app\project\backend

In [69]:
df = pd.read_csv("app/ml/datasets/archive/phish_tranco_140k_iteration2.csv")

In [87]:
df.head()

                         url  label
0  https://santander.com.uy/      0
1     https://www.stmus.com/      0
2  https://figurehunter.net/      0
3   https://www.porn963.com/      0
4   https://petswelcome.com/      0

In [77]:
benign_df =  pd.read_csv('app/ml/datasets/synthetic_legit_urls.csv')

In [78]:
benign_df["label"] = 0

In [79]:
benign_df = benign_df[["url", "label"]]

In [84]:
benign_df = benign_df[:600_000]

In [85]:
benign_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     600000 non-null  object
 1   label   600000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 9.2+ MB

In [86]:
benign_df.head()

                                                 url  label
0    https://www.softwar.io/ar/docidredir.aspx/atari      0
1  https://jaf.linksynergy.com/?id=418320&newsid=...      0
2  https://static.clientportal.link/ar/uploadscv/...      0
3   https://www.role-me.ru/faculty-arts-and-sciences      0
4                             https://www.kaya.in/v1      0

In [59]:
phish_df = pd.read_csv('app/ml/datasets/archive/phish_tranco_60k.csv')

In [60]:
phish_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117236 entries, 0 to 117235
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     117236 non-null  object
 1   label   117236 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.8+ MB

In [45]:
phish_df["label"] = 1

In [46]:
phish_df = phish_df[["url", "label"]]

In [61]:
phish_df.head()

                                                 url  label
0  https://www.r2b2.io/refclock.html/ar/newsdetai...      0
1  https://smartrg.com/d=1/robots.txt/documentati...      0
2  https://aau.gameanswers.net/ar/section-101/all...      0
3                    https://ccd.lnk.lt/v1/good-food      0
4  https://www.nextersglobal.com/en/2025-11-17-08...      0

In [88]:
#concat the two dataframes
df = pd.concat([benign_df, df], ignore_index=True)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743034 entries, 0 to 743033
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     743034 non-null  object
 1   label   743034 non-null  int64
dtypes: int64(1), object(1)
memory usage: 11.3+ MB

In [93]:
#check duplicates
df.duplicated().sum()

0

In [92]:
df.drop_duplicates(inplace=True)

In [94]:
df.head()

                                                 url  label
0    https://www.softwar.io/ar/docidredir.aspx/atari      0
1  https://jaf.linksynergy.com/?id=418320&newsid=...      0
2  https://static.clientportal.link/ar/uploadscv/...      0
3   https://www.role-me.ru/faculty-arts-and-sciences      0
4                             https://www.kaya.in/v1      0

In [95]:
df.value_counts("label")

label
0    665601
1     57229
Name: count, dtype: int64

In [97]:
# export df as csv file
df.to_csv("app/ml/datasets/archive/phish_tranco_740k_iteration3.csv", index=False)